from algorithm.backtracking import backtracking_line_search
from algorithm.bisection import bisection
from algorithm.exact_line_search import exact_line_search
from algorithm.function_on_line import function_on_line
from algorithm.gradient_descent import gradient_descent
from algorithm.newton import newton
